apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hackyeah-be.fullname" . }}
  labels:
    {{- include "hackyeah-be.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hackyeah-be.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hackyeah-be.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hackyeah-be.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: registry.gitlab.aexol.com/arkadiusz.kurylo/hackyeah/api:13df6a0d
          env:
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: {{ include "hackyeah-be.fullname" . }}
                key: MONGO_URL
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "hackyeah-be.fullname" . }}
                key: OPENAI_API_KEY
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /graphql
              port: http
          readinessProbe:
            httpGet:
              path: /graphql
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}3\
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
