apiVersion: v1
kind: Service
metadata:
  name: {{ include "hackyeah-be.fullname" . }}
  labels: {{- include "hackyeah-be.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "hackyeah-be.selectorLabels" . | nindent 4 }}
