# image.tag on command line
imagePullSecrets:
  - name: app-gitlab-project-regcred
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cf-dns-prod
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/cors-allow-methods: 'PUT, GET, POST, OPTIONS, DELETE'
  hosts:
    - host: hackyeah.project.aexol.work
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: hackyeah.project.aexol.work-tls
      hosts:
        - hackyeah.project.aexol.work
